---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-config
  namespace: mediacenter
  labels:
    app: couchpotato
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: couchpotato
  namespace: mediacenter
  labels:
    app: couchpotato
spec:
  ports:
    - name: cp-http
      port: 5050
      protocol: TCP
  selector:
    app: couchpotato
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchpotato
  namespace: mediacenter
  labels:
    app: couchpotato
spec:
  selector:
    matchLabels:
      app: couchpotato
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: couchpotato
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: linuxserver/couchpotato
        imagePullPolicy: Always
        name: couchpotato-container
        ports:
        - containerPort: 5050
        readinessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - mountPath: /config
          name: couchpotato-config
        - mountPath: /downloads
          name: downloads
        - mountPath: /movies
          name: movies
      volumes:
      - name: couchpotato-config
        persistentVolumeClaim:
          claimName: cp-config
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: movies
        persistentVolumeClaim:
          claimName: movies
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: couchpotato
  namespace: mediacenter
spec:
  rules:
  - host: couchpotato.playerof.games
    http:
     paths:
     - path: /
       backend:
        serviceName: couchpotato
        servicePort: cp-http
