---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: mediacenter
  labels:
    app: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: mediacenter
  labels:
    app: sabnzbd
spec:
  ports:
    - name: sabnzbd-http
      port: 8080
      protocol: TCP
  selector:
    app: sabnzbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: mediacenter
  labels:
    app: sabnzbd
spec:
  selector:
    matchLabels:
      app: sabnzbd
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: sabnzbd/sabnzbd
        imagePullPolicy: Always
        env:
          - name: HOST_WHITELIST_ENTRIES
            value: "sabnzbd.playerof.games"
        name: sabnzbd-container
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: /datadir
          name: sabnzbd-config
        - mountPath: /downloads
          name: downloads
        - mountPath: /media/series
          name: series
        - mountPath: /media/movies
          name: movies
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-config
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: series
        persistentVolumeClaim:
          claimName: series
      - name: movies
        persistentVolumeClaim:
          claimName: movies
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sabnzbd
  mamespace: mediacenter
spec:
  rules:
  - host: sabnzbd.playerof.games
    http:
     paths:
     - path: /
       backend:
        serviceName: sabnzbd
        servicePort: sabnzbd-http
