- name: wait for hosts to come up, upgrade if out of date
  hosts: OSEv3
  gather_facts: false
  pre_tasks:
  - name: "Wait for host up"
    local_action: wait_for
    args:
      host: "{{ inventory_hostname }}"
      port: 22
      state: started
      delay: 10
      timeout: 3600
  - setup:
  - set_fact:
      upgrade: true
  roles:
    - atomic_upgrade
    - role: reboot
      when: upgrade
